version: "3.8"
networks:
  insurance-network:

services:
  postgres:
    image: postgres:latest
    container_name: councilDB
    environment:
      - POSTGRES_DB=councilDB
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
    ports:
      - 5555:5432

  s3ninja:
    image: scireum/s3-ninja:latest
    container_name: file_storage
    ports:
      - "9444:9000"
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - S3NINJA_REGION=us-east-1
      - S3NINJA_ENDPOINT=http://localhost:9444/s3

  insurance_service:
    build:
      context: ../../../../../insurance-backend
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: insurance_service
    environment:
      QUARKUS_DATASOURCE_PASSWORD: 1234
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://insuranceDB:5432/insuranceDB
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_SMALLRYE_OPENAPI_ENABLE: TRUE
      QUARKUS_SMALLRYE_OPENAPI_PATH: /swagger
      QUARKUS_SWAGGER_UI_ENABLE: TRUE
      QUARKUS_SWAGGER_UI_PATH: /swagger-ui
    ports:
      - 8080:8080
    depends_on:
      - postgres
